pipeline {
    agent any
    stages {
        stage('Hello0') {
            steps {
                echo 'Hello World'
            }
        }

        stage('Hello1') {
            steps {
                echo 'Hello World'
            }
        }

        stage('Hello2') {
            steps {
                echo 'Hello World'
            }
        }


        stage('Hello3') {
            steps {
                echo 'Hello World'
            }
        }
    }
    post {
        success {
            slackSend color: '#2EB67D',
            channel: 'christelle-jenkins', 
            message: "Revive projet Build Status" +
            "\n Project Name: Revive" +
            "\n Job Name: ${env.JOB_NAME}" +
            "\n Build number: ${currentBuild.displayName}" +
            "\n Build Status : SUCCESS" +
            "\n Build url : ${env.BUILD_URL}"
        }
        failure {
            slackSend color: '#E01E5A',
            channel: 'christelle-jenkins',  
            message: "Revive projet Build Status" +
            "\n Project Name: Revive" +
            "\n Job Name: ${env.JOB_NAME}" +
            "\n Build number: ${currentBuild.displayName}" +
            "\n Build Status : FAILED" +
            "\n Build User : Christelle" +
            "\n Action : Please check the console output to fix this job IMMEDIATELY" +
            "\n Build url : ${env.BUILD_URL}"
        }
        unstable {
            slackSend color: '#ECB22E',
            channel: 'christelle-jenkins', 
            message: "Revive projet Build Status" +
            "\n Project Name: Revive" +
            "\n Job Name: ${env.JOB_NAME}" +
            "\n Build number: ${currentBuild.displayName}" +
            "\n Build Status : UNSTABLE" +
            "\n Action : Please check the console output to fix this job IMMEDIATELY" +
            "\n Build url : ${env.BUILD_URL}"
        }   
    }


}
        