pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}

    stages {

        stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}
 //    stage('Test microservice catalog') {
 //        agent {
 //            docker {
 //                image 'golang:1.20.1'
 //                args '-u 0:0'
 //            }
 //        }
 //        steps {
 //            sh '''
 //                cd $WORKSPACE/REVIVE/src/catalog/
 //                go test
 //            '''
 //        }
 //    }
 //    stage('Test microservice cart') {
 //        agent {
 //            docker {
 //                image 'maven:3.8.7-openjdk-18'
 //                args '-u 0:0'
 //            }
 //        }
 //        steps {
 //            sh '''
 //                cd $WORKSPACE/REVIVE/src/cart/
 //                mvn  test  -Dmaven.test.skip=true --quiet
 //            '''
 //        }
 //    }


 //    stage('Test microservice ui') {
 //        agent {
 //            docker {
 //                image 'maven:3.8.7-openjdk-18'
 //                args '-u 0:0'
 //            }
 //        }
 //        steps {
 //            sh '''
 //                cd $WORKSPACE/REVIVE/src/ui/
 //                mvn  test  -Dmaven.test.skip=true --quiet
 //            '''
 //        }
 //    }


 //    stage('Test microservice order') {
 //        agent {
 //            docker {
 //                image 'maven:3.8.7-openjdk-18'
 //                args '-u 0:0'
 //            }
 //        }
 //        steps {
 //            sh '''
 //                cd $WORKSPACE/REVIVE/src/orders/
 //                mvn  test  -Dmaven.test.skip=true --quiet
 //            '''
 //        }
 //    }

 //    stage('Test microservice checkout') {
 //        agent {
 //            docker {
 //                image 'node'
 //                args '-u 0:0'
 //            }
 //        }
 //        steps {
 //            sh '''
 //                cd $WORKSPACE/REVIVE/src/checkout/
 //                npm install
 //            '''
 //        }
 //    }
        



//      stage('SonarQube analysis') {
//                 agent {
//                     docker {
//                      image 'devopseasylearning/sonar-scanner-revive:v1.0.0'
//                    }
//                   }
//                   environment {
//            CI = 'true'
//            scannerHome='/opt/sonar-scanner'
//        }
//                steps{
//                    withSonarQubeEnv('sonar') {
//                        sh "${scannerHome}/bin/sonar-scanner"
//                    }
//                }
//            }
//        stage("Quality Gate") {
//                steps {
//                  timeout(time: 1, unit: 'HOURS') {
//                    waitForQualityGate abortPipeline: true
//                  }
//                }
//              }

//          stage('Build microservice catalog') {
//            agent {
//                docker {
//                    image 'golang:1.20.1'
//                    args '-u 0:0'
//                }
//            }
//            steps {
//                sh '''
//                    cd $WORKSPACE/REVIVE/src/catalog/
//                    go build   -buildvcs=false
//                '''
//            }
//        }
//
//        stage('Build microservice cart') {
//            agent {
//                docker {
//                    image 'maven:3.8.7-openjdk-18'
//                    args '-u 0:0'
//                }
//            }
//            steps {
//                sh '''
//                    cd $WORKSPACE/REVIVE/src/cart/
//                   mvn  package -Dmaven.test.skip=true --quiet
//                '''
//            }
//        }
//
//
//        stage('Build microservice ui') {
//            agent {
//                docker {
//                    image 'maven:3.8.7-openjdk-18'
//                    args '-u 0:0'
//                }
//            }
//            steps {
//                sh '''
//                    cd $WORKSPACE/REVIVE/src/ui/
//                    mvn  package -Dmaven.test.skip=true --quiet
//                '''
//            }
//        }
//
//        stage('Build microservice order') {
//            agent {
//                docker {
//                    image 'maven:3.8.7-openjdk-18'
//                    args '-u 0:0'
//                }
//            }
//            steps {
//                sh '''
//                    cd $WORKSPACE/REVIVE/src/orders/
//                    mvn  package -Dmaven.test.skip=true --quiet
//                '''
//            }
//        }
//
//
//        stage('Build microservice checkout') {
//            agent {
//                docker {
//                    image 'node'
//                    args '-u 0:0'
//                }
//            }
//            steps {
//                sh '''
//                    cd $WORKSPACE/REVIVE/src/checkout/
//                    npm install
//                    npm run build
//                '''
//            }
//        }
//
//
       stage('Build-images-ui') {
           steps {
               sh '''
           cd $WORKSPACE/REVIVE/src/ui/
           docker build -t  chnguemna/ui:jenkins-$BUILD_NUMBER .
               '''
           }
       }
       stage('Build-images-orders') {
           steps {
               sh '''
           cd $WORKSPACE/REVIVE/src/orders/
           docker build -t  chnguemna/orders:jenkins-$BUILD_NUMBER .
           docker build -f Dockerfile-rabbitmq  -t chnguemna/orders-rabbitmq:jenkins-$BUILD_NUMBER .
           docker build -f Dockerfile-mysql  -t chnguemna/orders-mysql:jenkins-$BUILD_NUMBER .


               '''
           }
       }

       stage('Build-images-cart') {
           steps {
               sh '''
           cd $WORKSPACE/REVIVE/src/cart/
           docker build -t  chnguemna/cart:jenkins-$BUILD_NUMBER .
           docker build -f Dockerfile-dynamodb -t chnguemna/cart-dynamodb:jenkins-$BUILD_NUMBER .
               '''
           }
       }


       stage('Build-images-assets') {
           steps {
               sh '''
           cd $WORKSPACE/REVIVE/src/assets/
           docker build -t  chnguemna/assets:jenkins-$BUILD_NUMBER .
               '''
           }
       }


       stage('Build-images-catalog') {
           steps {
               sh '''
           cd $WORKSPACE/REVIVE/src/catalog/
           docker build -t  chnguemna/catalog:jenkins-$BUILD_NUMBER .
           docker build -f Dockerfile-mysql -t chnguemna/catalog-mysql:jenkins-$BUILD_NUMBER .
               '''
           }
       }


       stage('Build-images-checkout') {
           steps {
               sh '''
           cd $WORKSPACE/REVIVE/src/checkout/
           docker build -t  chnguemna/checkout:jenkins-$BUILD_NUMBER .
           docker build -f Dockerfile-db -t chnguemna/checkout-db:jenkins-$BUILD_NUMBER .
               '''
           }
       }

       stage('Push-ui') {
          
            steps {
               sh 'docker push chnguemna/ui:jenkins-$BUILD_NUMBER'
            }
        }

      stage('Push-orders') {
        // Push-orders stage
            steps {
           
            sh '''
                docker push chnguemna/orders:jenkins-$BUILD_NUMBER
                docker push chnguemna/orders-rabbitmq:jenkins-$BUILD_NUMBER 
                docker push chnguemna/orders-mysql:jenkins-$BUILD_NUMBER
            '''
                }
        }

        stage('Push-cart') {
        // Push-orders stage
            steps {
           
            sh '''
                docker push chnguemna/cart:jenkins-$BUILD_NUMBER 
                docker push chnguemna/cart-dynamodb:jenkins-$BUILD_NUMBER 
                
            '''
                }
        }

        stage('Push-assets') {
          
            steps {
               sh 'docker push chnguemna/assets:jenkins-$BUILD_NUMBER'
            }
        }


        stage('Push-catalog') {
        // Push-orders stage
            steps {
           
            sh '''
                docker push chnguemna/catalog:jenkins-$BUILD_NUMBER 
                docker push chnguemna/catalog-mysql:jenkins-$BUILD_NUMBER  
                
            '''
                }
        }

        stage('Push-checkout') {
        // Push-orders stage
            steps {
           
            sh '''
                docker push chnguemna/checkout:jenkins-$BUILD_NUMBER
                docker push chnguemna/checkout-db:jenkins-$BUILD_NUMBER  
                
            '''
                }
        }


        stage('helm-charts') {


	      steps {
	        script {
	          withCredentials([
	            string(credentialsId: 'github_token', variable: 'TOKEN')
	          ]) {

	            sh '''
                rm -rf chris-revive-helm-chart || true 
                git clone https://github.com/s4christelle/chris-revive-helm-chart.git
                cd chris-revive-helm-chart
cat << EOF > dev-values.yaml
       repository:
         tag:   jenkins-$BUILD_NUMBER
         assets:
          image: chnguemna/assets
       
         carts:
          image: chnguemna/cart
       
         cart_dynamodb:
          image: chnguemna/cart-dynamodb
        
         catalog:
          image: chnguemna/catalog
       
        
         catalog_mysql:
          image: chnguemna/catalog-mysql
       
         checkout:
          image: chnguemna/checkout
       
         checkout_redis:
          image: chnguemna/checkout-redis
       
         orders:
          image: chnguemna/orders
       
         orders_mysql:
          image: chnguemna/orders-mysql
       
         orders_rabbitmq:
          image: chnguemna/orders-rabbitmq 
       
         ui:
          image: chnguemna/ui
EOF
git config --global user.name "chnguemna"
git config --global user.email "info@chnguemna.com"
   cat  dev-values.yaml
   
   git add -A 
    git commit -m "Change from JENKINS" 
    git push  https://chnguemna:$TOKEN@github.com/chnguemna/revive-helm-chart.git
	            '''
	          }

	        }

	      }

	    }
        

        

    
    }



 }        

